project:
  type: website
  output-dir: docs 
  render:   
    - "*.qmd"
    - "notebooks/*.ipynb"
    - "!notebooks/colab/"



execute:
  #enabled: false
  freeze: auto
  echo: true
  warning: false
  message: false
  

website: 
    
  description: "Practical guides for accessing, analyzing, and visualizing GRID3 data"
  site-url: https://tiles.ciesin.app/
  repo-url: https://github.com/ciesin/GRID3_dataUserGuide
  # repo-actions: [edit, issue]
  favicon: images/favicon.ico
  bread-crumbs: false

  

  navbar:
    logo: images/Columbia_University_Logo-Crown_white.png
    href: index.qmd
     

    # left:

    right:
      - icon: envelope-fill
        href: mailto:info@ciesin.columbia.edu
      - icon: database-fill
        href: https://data.grid3.org
      - icon: github
        href: https://github.com/ciesin/GRID3_dataUserGuide 
      - icon: linkedin
        href: https://www.linkedin.com/company/center-for-integrated-earth-system-information-ciesin/
      - icon: globe
        href: https://ciesin.columbia.edu



  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd

      - section: "Data Access"
        contents: 
          - notebooks/accessing_friction_surface_by_lga.qmd
          - notebooks/Roads_DRN_MD.qmd

      - section: "Analysis"
        contents:
          - notebooks/api_nga_network.ipynb 
          # - notebooks/folium-maps.ipynb
          # - notebooks/geopandas-plots.ipynb

      - section: "Visualization"
        contents:
          - notebooks/visualization-qgis.qmd

          - section: "Visualization with PMTiles"
            contents: 
            - notebooks/visualization-pmtiles-intro.qmd
            - notebooks/visualization-pmtiles.qmd

      - section: "Appendix"
        contents: 
          - notebooks/user_guide_template.qmd
          - notebooks/glossary.qmd


  google-analytics: 
    tracking-id: "G-45WWDMVLWW"
    anonymize-ip: true

  # body-footer: _footer.html
  page-footer:
    left: 
      - "© 2026 <a href='https://ciesin.columbia.edu'>Center for Integrated Earth System Information</a> (CIESIN), Columbia University."
 
    right:
      - icon: envelope-fill
        href: mailto:info@ciesin.columbia.edu
      - icon: database-fill
        href: https://data.grid3.org
      - icon: github
        href: https://github.com/ciesin/GRID3_dataUserGuide 
      - icon: linkedin
        href: https://www.linkedin.com/company/center-for-integrated-earth-system-information-ciesin/
      - icon: globe
        href: https://ciesin.columbia.edu



format:
  html:
    theme: default
    css: custom.css
    toc: true
    toc-location: right
    toc-depth: 4
    smooth-scroll: true
    code-copy: true
    number-sections: false
    fig-width: 6
    fig-height: 4
    fig-dpi: 120
    fig-alt-text: true
    lightbox: true
    navbar:
      type: default
    sidebar:
      collapse-level: 2
      float: false
      width: 300px 

    include-in-header: google-analytics.html
  



         